### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by icecreamsandwich** [pubudusj/load-balancer-with-lambda#1]
There is two terraform commands in deploy.sh script as `terraform plan -out tfout.plan
terraform apply tfout.plan`. But there are no tfout.plan file found in the repo, is it a typo or file is missed?

**Comment by pubudusj** [comment]
@icecreamsandwich 
Once you run the first command `terraform plan -out tfout.plan` , it will create the `tfout.plan`
And you can use the generated file in the next command: `terraform apply tfout.plan`
You may use any name for that file and not necessarily to be named as `tfout.plan`.

Of course you can directly run `terraform apply` instead of these 2 commands. But the best practice is to follow the two steps method: output the plan first and then apply it.

**Comment by icecreamsandwich** [comment]
Oh, now I got it. Thanks, @pubudusj  for the reply. will try this. BTW This ALB can be deployed before any application to manage the load right?

**Comment by pubudusj** [comment]
@icecreamsandwich You may add other target groups (ex: ec2s) to the ALB created. Initial set up is to use Lambda as the target.
